services:
  db:
    image: postgres:13.0-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - SQL_USER=bookstore_dev
      - SQL_PASSWORD=bookstore_dev
      - SQL_DB=bookstore_dev_db

  web:
    build: .
    command: ./wait-for-it.sh db:5432 -- python manage.py runserver 0.0.0.0:8000
    volumes:
      - app_data:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db

volumes:
  postgres_data:
  app_data: